/*
Find the number of times the words 'bull' and 'bear' occur in the contents. 

We're counting the number of times the words occur so words like 'bullish' should not be included in our count.

Output the word 'bull' and 'bear' along with the corresponding number of occurrences.

google_file_store
filename:   varchar
contents:   varchar
*/


-- ATTEMPT: CTE with REGEXP_REPLACE(UNNEST(STRING_TO_ARRAY))
With Words AS (
    SELECT
        -- Remove non-alphanumeric characters
        REGEXP_REPLACE(
            -- Unnest the split string into multiple rows for each word in the string
            UNNEST(
                -- split the string by a delimiter (comma)
                STRING_TO_ARRAY(contents, ' ')
            ),
            '\W+', -- \W is the same as [^a-zA-Z0-9_] = find all non-alphanumeric/word character, + = one to unlimited times
            '', -- replace with blank character
            'g' -- instructs the function to remove all non-alphanumerics, not just the first one.        
        ) AS word
    FROM google_file_store
    -- LIMIT 20
)

SELECT
    word,
    COUNT(word)
FROM Words
WHERE LOWER(word) IN ('bull', 'bear')
GROUP BY word
;


-- ATTEMPT 2: Same thing, slightly different notes
WITH all_words AS (
    SELECT
        -- *,
        REGEXP_REPLACE(
            -- Convert a text block to an array and then unnest into a record per word
            UNNEST(STRING_TO_ARRAY(contents, ' ')) -- AS test
        -- Find all NON-alphanumeric characters/words, (+) one-to-unlimited times
        , '\W+'
        -- Replace with blank
        , ''
        -- Do so for all instances, not just the first one found
        , 'g'
        ) AS word
    FROM google_file_store
    -- LIMIT 3 -- only 3 records
)

SELECT
    word,
    COUNT(word)
FROM all_words
WHERE LOWER(word) in ('bear', 'bull')
GROUP BY word
;


-- SOLUTION:
-- TS_STATS function used to count the occurrences of words in the provided text. 
--  - Takes a TSVECTOR as input, which is generated by the TO_TSVECTOR function
--  - The subquery `SELECT TO_TSVECTOR(contents) FROM google_file_store` generates a TSVECTOR based on the contents column.
SELECT 
    word,
    nentry                                       
FROM  
    TS_STAT('SELECT TO_TSVECTOR(contents) FROM google_file_store') 
WHERE
    word ILIKE 'bull' OR word ILIKE 'bear'