/*
Find the number of times the words 'bull' and 'bear' occur in the contents. 

We're counting the number of times the words occur so words like 'bullish' should not be included in our count.

Output the word 'bull' and 'bear' along with the corresponding number of occurrences.

google_file_store
filename:   varchar
contents:   varchar
*/


-- ATTEMPT: CTE with REGEXP_REPLACE(UNNEST(STRING_TO_ARRAY))
With Words AS (
    SELECT
        -- Remove non-alphanumeric characters
        REGEXP_REPLACE(
            -- Unnest the split string into multiple rows for each word in the string
            UNNEST(
                -- split the string by a delimiter (comma)
                STRING_TO_ARRAY(contents, ' ')
            ),
            '\W+', -- \W is the same as [^a-zA-Z0-9_]
            '', -- replace with blank character
            'g' -- instructs the function to remove all alphabets, not just the first one.        
        ) AS word
    FROM google_file_store
    -- LIMIT 20
)

SELECT
    word,
    COUNT(word)
FROM Words
WHERE LOWER(word) IN ('bull', 'bear')
GROUP BY word
;


-- SOLUTION:
-- TS_STATS function used to count the occurrences of words in the provided text. 
--  - Takes a TSVECTOR as input, which is generated by the TO_TSVECTOR function
--  - The subquery `SELECT TO_TSVECTOR(contents) FROM google_file_store` generates a TSVECTOR based on the contents column.
SELECT 
    word,
    nentry                                       
FROM  
    TS_STAT('SELECT TO_TSVECTOR(contents) FROM google_file_store') 
WHERE
    word ILIKE 'bull' OR word ILIKE 'bear'